# Generated by Django 4.0.4 on 2022-11-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsAlertBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_bot_token', models.CharField(max_length=200, verbose_name='Токен')),
                ('alert_bot_chat_id', models.CharField(max_length=200, verbose_name='Айди чата')),
                ('alert_bot_text_message', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
            },
        ),
    ]
