# Generated by Django 4.0.4 on 2022-08-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_discount_remove_product_discount_discount_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('value',), 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='discount_product',
            options={'verbose_name': 'Скидка и название товара', 'verbose_name_plural': 'Скидки и название товара'},
        ),
        migrations.AddField(
            model_name='discount_product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
