# Generated by Django 4.0.4 on 2022-08-28 22:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_product',
            name='end',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 28, 22, 53, 17, 815198, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount_product',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 28, 22, 53, 20, 90093, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
