# Generated by Django 4.0.4 on 2022-08-29 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_discount_product_end_discount_product_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 12, 33, 30, 814578, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discount_product',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 12, 33, 30, 814578, tzinfo=utc)),
        ),
    ]
