# Generated by Django 4.0.4 on 2022-08-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_discount_product_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.review', verbose_name='Родитель'),
        ),
        migrations.DeleteModel(
            name='Review_answer',
        ),
    ]
