# Generated by Django 4.0.4 on 2022-08-29 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_review_review_text_review_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
