# Generated by Django 4.0.4 on 2022-09-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_favorites_unique_together_categoryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'verbose_name': 'Фотография категории', 'verbose_name_plural': 'Фотографии категории'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография продукта', 'verbose_name_plural': 'Фотографии продуктов'},
        ),
        migrations.RemoveField(
            model_name='categoryimage',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='cat_product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='cat_product_images/'),
        ),
    ]
