# Generated by Django 4.0.4 on 2022-09-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_categoryimage_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
