# Generated by Django 4.0.4 on 2022-09-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_productimage_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product'),
        ),
    ]
