# Generated by Django 4.0.4 on 2022-09-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ManyToManyField(blank=True, default=None, to='shop.product'),
        ),
    ]
