# Generated by Django 4.0.4 on 2022-09-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_product_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.CreateModel(
            name='ProductAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childer', to='shop.product')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='shop.product')),
            ],
        ),
    ]
