# Generated by Django 4.0.4 on 2022-09-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_product_parent_productaccessories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productaccessories',
            options={'verbose_name': 'Аксесуар', 'verbose_name_plural': 'Аксесуары'},
        ),
    ]
