# Generated by Django 4.0.4 on 2022-10-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_review_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
    ]
