# Generated by Django 4.0.4 on 2022-10-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
    ]
