# Generated by Django 4.0.4 on 2022-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_category_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAccessories',
            new_name='ProductRecommendations',
        ),
        migrations.AlterModelOptions(
            name='productrecommendations',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='categoryimage',
            table='CategoryImage',
        ),
        migrations.AlterModelTable(
            name='discount',
            table='Discount',
        ),
        migrations.AlterModelTable(
            name='favorites',
            table='Favorites',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='ProductImage',
        ),
        migrations.AlterModelTable(
            name='productrecommendations',
            table='ProductRecommendations',
        ),
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
