# Generated by Django 4.0.4 on 2022-10-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_rename_productaccessories_productrecommendations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.адрес обратной связи')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщения от пользователей',
                'verbose_name_plural': 'Сообщения от пользователей',
                'db_table': 'MessageForUser',
            },
        ),
    ]
