# Generated by Django 4.0.4 on 2022-10-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_messagefromuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messagefromuser',
            table='MessageFromUser',
        ),
    ]
