# Generated by Django 4.0.4 on 2022-10-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_messagefromuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAnswerForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
