# Generated by Django 4.0.4 on 2022-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_messageanswerforuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefromuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
