# Generated by Django 4.0.4 on 2022-11-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_alter_rating_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageanswerforuser',
            options={'verbose_name': 'Сообщения для пользователей', 'verbose_name_plural': 'Сообщения для пользователей'},
        ),
        migrations.AlterModelTable(
            name='messageanswerforuser',
            table='MessageAnswerForUser',
        ),
    ]
