# Generated by Django 4.0.4 on 2022-11-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageanswerforuser',
            name='message_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.messagefromuser'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='messageanswerforuser',
            unique_together={('message_user',)},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'slug')},
        ),
    ]
