# Generated by Django 4.0.5 on 2022-07-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliverymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.deliverymethod'),
            preserve_default=False,
        ),
    ]
