# Generated by Django 4.0.4 on 2022-11-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_order_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default='XDblD3', max_length=6, verbose_name='Cекретный ключ'),
        ),
    ]
