# Generated by Django 4.0.4 on 2022-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='799zkf', max_length=6, verbose_name='Cекретный ключ'),
        ),
    ]
