# Generated by Django 4.0.4 on 2022-11-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('В магазине', 'В магазине'), ('На складе', 'На складе'), ('В пути', 'В пути'), ('Получен', 'Получен')], default='В обработке', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='5rKwtH', max_length=6, verbose_name='Cекретный ключ'),
        ),
    ]
